name: owlsnest
favicon: null
layout_spectrum: 0.5165571090765297
typography_spectrum: 0.7218663380481303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3282633756753057
  lightness: 0.7683985950425267
  saturation: 0.10504414024762809
  rhythmicContrast: 0.10972234257496893
purpose: []
